-- DATA 262: Lab 1
-- Weather Data Pipeline

USE DATABASE USER_DB_BULLFROG;
USE SCHEMA RAW;

-- Creating weather data table
CREATE TABLE IF NOT EXISTS WEATHER_DATA_LAB1 (
    CITY STRING,
    DATE DATE,
    TEMP_MAX FLOAT,
    TEMP_MEAN FLOAT,
    PRECIPITATION FLOAT
);

-- Viewing Data
SELECT CITY, COUNT(*)
FROM WEATHER_DATA_LAB1
GROUP BY CITY;
